#base ../../../cfg/killfeed-streamer.txt
#base ../../../cfg/hud_crosshair.txt
#base ../../../cfg/hud_crosshair_size.txt
#base ../../../cfg/hud_xhair_colors.txt
#base ../../../cfg/hud_hitmarker.txt
#base ../../../cfg/hud_hitmarker_size.txt
#base ../../../cfg/hud_hmark_colors.txt
#base ../../../cfg/hud_vmodel_transparency.txt
#base ../../../cfg/hudlayout_res.txt
#base ../../../cfg/ultrahud_shader.txt
"#base" "hudlayout-base.res"